name: utility_paper
channels:
  - conda-forge
  - gurobi
dependencies:		
  - contourpy=1.2.0	
  - cycler=0.11.0		
  - fonttools=4.51.0
  - gurobi		
  - kiwisolver=1.4.4		
  - numpy=1.26.4		
  - openpyxl=3.1.2		
  - packaging=23.2	
  - pandas=2.2.1	
  - pillow=10.3.0	
  - pip=24.0	
  - plotly=5.22.0	
  - ply=3.11	
  - Pyomo=6.7.2	
  - pyparsing=3.0.9			
  - python-dateutil=2.9.0
  - python-tzdata=2023.3		
  - pytz=2024.1		
  - setuptools=69.5.1			
  - wheel=0.43.0			